name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@1.60.0
    - uses: Swatinem/rust-cache@v2
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libdbus-1-dev pkg-config
      if: ${{ runner.os == 'Linux' }}
    - name: Build
      run: cargo build --release --all-targets --verbose
    - name: Build zbus
      run: cargo build --release --all-targets --verbose --no-default-features --features=use_zbus
      if: ${{ runner.os == 'Linux' }}
